task:
  freebsd_instance:
    matrix:
      - image_family: freebsd-13-2
      - image_family: freebsd-14-0

  environment:
    CFLAGS: -O2 -pipe -fPIC -fstack-protector-strong -fno-strict-aliasing -I/usr/local/include
    CPPFLAGS: -O2 -pipe -fPIC -fstack-protector-strong -fno-strict-aliasing -I/usr/local/include
    LDFLAGS: -lreadline -L/usr/local/lib -fstack-protector-strong

  jack2_dependencies_script:
    - pkg install -y jackit pkgconf python3 libsndfile libsamplerate libsysinfo readline alsa-lib dbus expat opus git

  prepare_script:
    - mkdir -p /Install/include
  dependencies_script:
    - pkg install -y pkgconf python3 libsndfile libsamplerate libsysinfo readline alsa-lib zita-alsa-pcmi zita-resampler opus meson ninja
  config_script:
    - meson --prefix /Install --mandir man --buildtype release --strip build
  build_script:
    - ninja -C build
  install_script:
    - DESTDIR="/Install" meson install -C build
