#!/usr/bin/env sh
#
# Installs man pages with .1 suffix in $MESON_BUILD_ROOT to man_dir ($1) below
# $MESON_INSTALL_DESTDIR_PREFIX

set -eu

man_dir="$1"

install -vDm 644 "${MESON_BUILD_ROOT}/man/"*.1 \
        -t "${MESON_INSTALL_DESTDIR_PREFIX}/${man_dir}/man1"
